version: 2.1

# using service containers on CircleCI
# https://github.com/cypress-io/circleci-orb/blob/master/docs/recipes.md#service-containers
# https://circleci.com/docs/2.0/databases/
executors:
  with-mongo:
    docker:
      - image: cypress/base:14.16.0
        environment:
          MONGODB_URI: mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@localhost:27017/?authSource=admin

      - image: mongo:4.4.5
        environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
workflows:
  build:
    jobs:
      - cypress/run:
          executor: with-mongo
          start: npm test
          # no need to save the workspace after this job
          no-workspace: true

